version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:3000"
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=sigap_db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sigap_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

  # --- LAYANAN BARU UNTUK MANAJEMEN DATABASE ---
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data: